# doracxx.toml - Configuration for Dora C++ nodes

[node]
name = "my-node"
type = "node"  # or "processor"
dora_version = "0.3.5"  # optional: specific Dora version
# dora_git = "https://github.com/dora-rs/dora"  # optional: custom Dora repository
# dora_rev = "main"  # optional: specific revision/branch/tag
description = "My awesome Dora C++ node"
version = "0.1.0"

[build]
# Toolchain selection: "auto", "gcc", "clang", "msvc"
toolchain = "auto"

# Build system: "native", "cmake", "make", "ninja"
system = "native"

# Build profile: "debug" or "release"
profile = "debug"

# C++ standard: "c++11", "c++14", "c++17", "c++20", "c++23"
std = "c++17"

# Additional compiler flags
cflags = ["-Wall"]
cxxflags = ["-Wall", "-Wextra"]
ldflags = []

# Additional include and library paths
include_dirs = ["include", "deps/custom/include"]
lib_dirs = ["lib"]
libraries = ["pthread"]

# Source files configuration
# If not specified, all .cpp/.cc files in src/ will be included
# sources = ["src/main.cc", "src/processor.cc"]
# Exclude patterns for source files (optional)
# exclude_sources = ["**/*test*.cpp", "**/*test*.cc", "test_*.cpp", "test_*.cc"]

# CMake specific options (when system = "cmake")
[build.cmake_options]
CMAKE_BUILD_TYPE = "Debug"
BUILD_TESTING = "OFF"

# Enable automatic clang installation if not found (Windows)
install_clang = false

# Parallel compilation jobs (default: auto-detect)
# parallel_jobs = 4

[dependencies]
# Git dependency example
[dependencies.eigen]
type = "git"
url = "https://gitlab.com/libeigen/eigen.git"
tag = "3.4.0"
build_system = "cmake"
include_dirs = ["eigen3"]

[dependencies.eigen.cmake_options]
BUILD_TESTING = "OFF"
EIGEN_BUILD_DOC = "OFF"

# vcpkg dependency example  
[dependencies.opencv]
type = "vcpkg"
name = "opencv"
version = "4.8.0"
features = ["contrib", "ffmpeg"]
triplet = "x64-windows"  # optional, auto-detected by default

# System dependency example
[dependencies.boost]
type = "system"
name = "boost"
pkg_config = "boost"
libraries = ["boost_system", "boost_filesystem"]

# Local dependency example
[dependencies.mylib]
type = "local"
path = "../mylib"
build_system = "cmake"
include_dirs = ["include"]
libraries = ["mylib"]
