version: '3'

tasks:
  default:
    cmds:
    - task: example:build-simple-node
  example:build-simple-node:
    deps: [example:create-venv]
    desc: "Build and run the 'simple-node' example using doracxx"
    dir: "./examples"
    cmds:
      - uv run doracxx build --node-dir simple-node --profile release --out simple-node
  example:prepare-dora-full:
    dir: "./examples"
    deps:
      - example:create-venv
    desc: "Setup Dora for the example (full workspace build - slower but complete)"
    cmds:
      - uv run doracxx prepare --full-workspace

  example:create-venv:
    desc: "Create virtual environment with uv"
    dir: "./examples"
    cmds:
      - uv venv
      - uv pip install -e ../
    status:
      - test -d .venv