# doracxx.toml - Configuration for Dora C++ nodes
# This is an example configuration file for the simple-node example

[node]
name = "simple-node"
type = "node"  # or "processor"
description = "Simple example Dora C++ node with Eigen3"
version = "0.1.0"

[build]
# Toolchain selection: "auto", "gcc", "clang", "msvc"
toolchain = "auto"

# Build system: "native", "cmake", "make", "ninja"
system = "native"

# Build profile: "debug" or "release"
profile = "debug"

# C++ standard: "c++11", "c++14", "c++17", "c++20", "c++23"
std = "c++17"

# Additional compiler flags
cflags = ["-Wall"]
cxxflags = ["-Wall", "-Wextra"]
ldflags = []

# Additional include and library paths
include_dirs = ["include"]
lib_dirs = []
libraries = []

# Enable automatic clang installation if not found (Windows)
install_clang = false

[dependencies]
# Eigen3 dependency example
[dependencies.eigen3]
type = "git"
url = "https://gitlab.com/libeigen/eigen.git"
tag = "3.4.0"
build_system = "cmake"
include_dirs = ["include/eigen3"]

[dependencies.eigen3.cmake_options]
BUILD_TESTING = "OFF"
EIGEN_BUILD_DOC = "OFF"
EIGEN_BUILD_PKGCONFIG = "OFF"
