# doracxx.toml - Minimal configuration for Dora C++ node

[node]
name = "simple-node"
type = "node"
description = "Minimal Dora C++ node configuration"
version = "0.1.0"

[build]
toolchain = "auto"
system = "native"
profile = "debug"
std = "c++17"
